name: Build, Test, and Deploy {{ secrets.DOCKER_IMAGE_NAME_BACKEND }}

on:
  push:
    branches:
      - main
    paths:
      - 'code-pulse-api/**'
  pull_request:
    branches:
      - main
    paths:
      - 'code-pulse-api/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Run Unit Tests
      run: mvn test
      working-directory: ./code-pulse-api 

    - name: Build with Maven
      run: mvn clean install
      working-directory: ./code-pulse-api   

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Docker Build and Tag
      run: |
        docker build -t ${{ secrets.DOCKER_IMAGE_NAME_BACKEND }} .
      working-directory: ./code-pulse-api

    - name: Push Docker Image
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker push ${{ secrets.DOCKER_IMAGE_NAME_BACKEND }}
